/* =======================================================================
   CAIRN schema bootstrap
   -----------------------------------------------------------------------
   • Create enums  : rate_impact_enum, quality_check_enum
   • Create table  : public.files          (if missing)
   • Add columns   : any not already present – see JSON map
   ======================================================================= */
begin;

set search_path = public;

/* ───────────────────────── ENUMS (idempotent) ───────────────────────── */
do
$$
begin
  if not exists (select 1 from pg_type where typname = 'rate_impact_enum') then
    execute $$create type rate_impact_enum
             as enum ('Yes','No','Partial')$$;
  end if;

  if not exists (select 1 from pg_type where typname = 'quality_check_enum') then
    execute $$create type quality_check_enum
             as enum ('Complete','Pending','Needs Review')$$;
  end if;
end
$$;

/* ───────────────────────── TABLE shell (idempotent) ─────────────────── */
create table if not exists files (
  id bigint generated by default as identity primary key
);

/* ───────────────────────── ADD missing columns ──────────────────────── */
do
$$
declare
  cols jsonb := '{
    "document_id"          : "text unique",
    "source_file_id"       : "text",
    "local_backup_name"    : "text",
    "document_title"       : "text",
    "published_date"       : "date",
    "org_utility_name"     : "text",
    "docket_number"        : "text",
    "document_type"        : "text",
    "document_subtype"     : "text",
    "file_format"          : "text",
    "document_url"         : "text",
    "cairn_url"            : "text",

    "rate_impact"          : "rate_impact_enum",
    "physical_climate_risk": "boolean",

    "utility_reform"       : "text[]",
    "energy_resources"     : "text[]",
    "customer_classes"     : "text[]",
    "ders"                 : "text[]",
    "additional_keywords"  : "text[]",
    "related_documents"    : "text[]",
    "relationship_types"   : "text[]",

    "tagger"               : "text",
    "date_tagged"          : "date",
    "quality_check"        : "quality_check_enum",
    "processing_notes"     : "text",

    "state_region"         : "text",
    "regulatory_body"      : "text",
    "jurisdiction_type"    : "text",

    "parent_document"      : "text",
    "replaces_document"    : "text",

    "b2_file_id"           : "text",
    "b2_temp_url"          : "text",
    "last_synced_at"       : "timestamptz default now()",
    "updated_at"           : "timestamptz default now()"
  }';

  col_name text;
  col_def  text;
begin
  for col_name, col_def in
      select key, value::text from jsonb_each_text(cols)
  loop
    if not exists (
      select 1
      from information_schema.columns
      where table_schema = 'public'
        and table_name   = 'files'
        and column_name  = col_name
    ) then
      execute format(
        'alter table files add column %I %s;',
        col_name, col_def
      );
    end if;
  end loop;
end
$$;

/* ───────────────────────── Force PostgREST cache refresh ────────────── */
comment on table files is 'schema refreshed ' || now();

commit;
